"""
Django settings for twin4dem project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django_vite import DjangoViteConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5v5lw%466qj#e3v^1qw49j7e0kmszoxxk#!o1)_bxon@bhuarh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = ["http://localhost:8000"]
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.microsoft",
    "django_vite",
    "web",
    "simulator",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "twin4dem.urls"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "twin4dem.wsgi.application"
ASGI_APPLICATION = "twin4dem.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("TWIN4DEM_BACKEND_DB_NAME", "twin4dem"),
        "USER": os.getenv("TWIN4DEM_BACKEND_DB_USER", "twin4dem"),
        "PASSWORD": os.getenv("TWIN4DEM_BACKEND_DB_PASS", "twin4dem"),
        "HOST": os.getenv("TWIN4DEM_BACKEND_DB_HOST", "localhost"),
        "PORT": int(os.getenv("TWIN4DEM_BACKEND_DB_PORT", 5432)),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "static"
FRONTEND_ROOT = STATIC_ROOT / "frontend"
STATICFILES_DIRS = [FRONTEND_ROOT]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Vite
VITE_DEV_MODE = str(os.getenv("TWIN4DEM_BACKEND_VITE_DEV_MODE", True)).lower() in {"y", "yes", "true", "1"}
DJANGO_VITE = {
    "default": DjangoViteConfig(
        dev_mode=VITE_DEV_MODE,
        dev_server_port=3000,
        manifest_path=FRONTEND_ROOT / ".vite" / "manifest.json",
    )
}

REDIS_HOST = os.getenv("TWIN4DEM_BACKEND_REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("TWIN4DEM_BACKEND_REDIS_PORT", 6379))
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CELERY_USER = os.getenv("TWIN4DEM_BACKEND_CELERY_USER", "twin4dem")
CELERY_PASS = os.getenv("TWIN4DEM_BACKEND_CELERY_PASS", "twin4dem")
CELERY_HOST = os.getenv("TWIN4DEM_BACKEND_CELERY_HOST", "localhost")
CELERY_PORT = int(os.getenv("TWIN4DEM_BACKEND_CELERY_PORT", 5672))
CELERY_BROKER_URL = f"amqp://{CELERY_USER}:{CELERY_PASS}@{CELERY_HOST}:{CELERY_PORT}//"
CELERY_RESULT_BACKEND = "rpc://"
