# Generated by Django 5.2.8 on 2025-12-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="default", max_length=50)),
                ("government_size", models.PositiveSmallIntegerField(default=15)),
                (
                    "government_connectivity_degree",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("parliament_size", models.PositiveSmallIntegerField(default=100)),
                ("court_size", models.PositiveSmallIntegerField(default=5)),
                ("abstention_threshold", models.FloatField(default=0.2)),
                ("data_update_frequency", models.PositiveSmallIntegerField(default=10)),
                ("legislative_path_probability", models.FloatField(default=0.5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User settings",
                "verbose_name_plural": "User settings",
            },
        ),
        migrations.CreateModel(
            name="PartySettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("member_count", models.PositiveSmallIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("majority", "Majority"),
                            ("opposition", "Opposition"),
                            ("independent", "Independent"),
                        ]
                    ),
                ),
                (
                    "user_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="common.usersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "member_count"],
            },
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("abstention_threshold__gte", 0.0),
                    ("abstention_threshold__lte", 1.0),
                ),
                name="ck_usersettings_abstention_threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legislative_path_probability__gte", 0.0),
                    ("legislative_path_probability__lte", 1.0),
                ),
                name="ck_usersettings_legislative_path_probability",
            ),
        ),
    ]
