# Generated by Django 6.0.1 on 2026-10-04 10:31

import common.fields._sv_field
import common.models._simulation
import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import typing
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AggrandisementBatch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="MemberOfParliament",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "weights",
                    common.fields._sv_field.SeparatedValuesField(
                        base_field=models.FloatField(), blank=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartySettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("member_count", models.PositiveSmallIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("majority", "Majority"),
                            ("opposition", "Opposition"),
                            ("independent", "Independent"),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["position", "member_count"],
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="new",
                    ),
                ),
                ("current_step", models.PositiveBigIntegerField(default=0)),
                ("office_retention_sensitivity", models.FloatField(default=5.0)),
                ("social_influence_susceptibility", models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name="AggrandisementUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("step_no", models.PositiveIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="common.aggrandisementbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("government_probability_for", models.FloatField(default=0.5)),
                ("legislative_probability", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("government_probability_for__gte", 0),
                            ("government_probability_for__lte", 1),
                        ),
                        name="ck_government_probability_for_is_prob",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("probability_for", models.FloatField(default=0.5)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("probability_for__gte", 0), ("probability_for__lte", 1)
                        ),
                        name="ck_court_probability_for_is_prob",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InstitutionTaxonomy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ]
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy",
                        to="common.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Institution taxonomies",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                ("size", models.PositiveSmallIntegerField()),
                (
                    "serialization_model",
                    models.CharField(
                        choices=[
                            ("cabinet", "Cabinet"),
                            ("chamber", "Chamber"),
                            ("court", "Court"),
                        ]
                    ),
                ),
                ("serialization_version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "institution_taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutions",
                        to="common.institutiontaxonomy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("influence", models.FloatField(default=0.0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("is_president", models.BooleanField(default=False)),
                (
                    "weights",
                    common.fields._sv_field.SeparatedValuesField(
                        base_field=models.FloatField(), blank=True
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judges",
                        to="common.court",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JudgeBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.judge",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judges",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JudgeLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "from_judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="common.judge",
                    ),
                ),
                (
                    "to_judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="common.judge",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="judge",
            name="neighbours_out",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="neighbours_in",
                through="common.JudgeLink",
                to="common.judge",
            ),
        ),
        migrations.CreateModel(
            name="Minister",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("influence", models.FloatField(default=0.0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("is_prime_minister", models.BooleanField(default=False)),
                (
                    "weights",
                    common.fields._sv_field.SeparatedValuesField(
                        base_field=models.FloatField(), blank=True
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministers",
                        to="common.cabinet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinisterBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.minister",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministers",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinisterLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "from_minister",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="common.minister",
                    ),
                ),
                (
                    "to_minister",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="common.minister",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minister",
            name="neighbours_out",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="neighbours_in",
                through="common.MinisterLink",
                to="common.minister",
            ),
        ),
        migrations.CreateModel(
            name="MPBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.memberofparliament",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mps",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parliament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("majority_probability_for", models.FloatField(default=0.5)),
                ("opposition_probability_for", models.FloatField(default=0.5)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("majority_probability_for__gte", 0),
                            ("majority_probability_for__lte", 1),
                        ),
                        name="ck_majority_probability_for_is_prob",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("opposition_probability_for__gte", 0),
                            ("opposition_probability_for__lte", 1),
                        ),
                        name="ck_opposition_probability_for_is_prob",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="memberofparliament",
            name="parliament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="common.parliament",
            ),
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="common.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="PartyPosition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("majority", "Majority"),
                            ("opposition", "Opposition"),
                            ("independent", "Independent"),
                        ]
                    ),
                ),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_positions",
                        to="common.institution",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="common.party",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minister",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ministers",
                to="common.partysettings",
            ),
        ),
        migrations.AddField(
            model_name="memberofparliament",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="mps",
                to="common.partysettings",
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="judges",
                to="common.partysettings",
            ),
        ),
        migrations.AddField(
            model_name="aggrandisementbatch",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch",
                to="common.simulation",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="SimulationLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("step_no", models.IntegerField()),
                ("approved", models.BooleanField()),
                (
                    "last_decision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "aggrandisement_path",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("decree", "Decree"),
                            ("legislative act", "Legislative Act"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="common.simulation",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_log",
            },
        ),
        migrations.CreateModel(
            name="SimulationParams",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.PositiveBigIntegerField()),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="common.simulation",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationSubmodelLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "submodel_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ]
                    ),
                ),
                ("approved", models.BooleanField()),
                (
                    "additional_info",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing.Union,
                            (
                                common.models._simulation.PathSubmodelInfo,
                                common.models._simulation.VbarSubmodelInfo,
                            ),
                        ),
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submodels",
                        to="common.simulationlogentry",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_submodel_log",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="default", max_length=50)),
                ("government_probability_for", models.FloatField(default=0.5)),
                ("parliament_majority_probability_for", models.FloatField(default=0.5)),
                (
                    "parliament_opposition_probability_for",
                    models.FloatField(default=0.5),
                ),
                ("court_probability_for", models.FloatField(default=0.5)),
                ("office_retention_sensitivity", models.FloatField(default=5.0)),
                ("social_influence_susceptibility", models.FloatField(default=0.5)),
                ("abstention_threshold", models.FloatField(default=0.2)),
                ("data_update_frequency", models.PositiveSmallIntegerField(default=10)),
                ("legislative_path_probability", models.FloatField(default=0.5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User settings",
                "verbose_name_plural": "User settings",
            },
        ),
        migrations.AddField(
            model_name="simulation",
            name="user_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations",
                to="common.usersettings",
            ),
        ),
        migrations.AddField(
            model_name="partysettings",
            name="user_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="common.usersettings",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="user_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="common.usersettings",
            ),
        ),
        migrations.CreateModel(
            name="VirtualTimeline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="default", max_length=50)),
                (
                    "user_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelines",
                        to="common.usersettings",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aggrandisementunit",
            constraint=models.UniqueConstraint(
                fields=("step_no", "batch"), name="uq_step_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="institutiontaxonomy",
            constraint=models.UniqueConstraint(
                fields=("country", "type"), name="uq_institutiontaxonomy_country_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="institutiontaxonomy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("branch__in", ["executive", "legislative", "judiciary"])
                ),
                name="ck_institutiontaxonomy_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("institution_taxonomy", "label"),
                name="uq_institution_taxonomy_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("serialization_model__in", ["cabinet", "chamber", "court"])
                ),
                name="ck_institution_serialization_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.CheckConstraint(
                condition=models.Q(("serialization_version__gte", 1)),
                name="ck_institution_serialization_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="judgebelief",
            constraint=models.UniqueConstraint(
                fields=("agent", "unit"), name="uq_judge_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgelink",
            constraint=models.UniqueConstraint(
                fields=("from_judge", "to_judge"),
                name="uq_judgelink_no_duplicate_edges",
            ),
        ),
        migrations.AddConstraint(
            model_name="judgelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_judge", models.F("to_judge")), _negated=True),
                name="ck_judgelink_no_self_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="ministerbelief",
            constraint=models.UniqueConstraint(
                fields=("agent", "unit"), name="uq_minister_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="ministerlink",
            constraint=models.UniqueConstraint(
                fields=("from_minister", "to_minister"),
                name="uq_ministerlink_no_duplicate_edges",
            ),
        ),
        migrations.AddConstraint(
            model_name="ministerlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_minister", models.F("to_minister")), _negated=True
                ),
                name="ck_ministerlink_no_self_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="mpbelief",
            constraint=models.UniqueConstraint(
                fields=("agent", "unit"), name="uq_mp_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.UniqueConstraint(
                fields=("country", "label"), name="uq_party_country_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__in", ["majority", "opposition", "independent"])
                ),
                name="ck_partyposition_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="minister",
            constraint=models.CheckConstraint(
                condition=models.Q(("influence__gte", 0.0), ("influence__lte", 1.0)),
                name="ck_minister_influence",
            ),
        ),
        migrations.AddConstraint(
            model_name="minister",
            constraint=models.UniqueConstraint(
                fields=("label", "cabinet"), name="uq_minister_label_in_cabinet"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberofparliament",
            constraint=models.UniqueConstraint(
                fields=("label", "parliament"), name="uq_mp_label_in_parliament"
            ),
        ),
        migrations.AddConstraint(
            model_name="judge",
            constraint=models.CheckConstraint(
                condition=models.Q(("influence__gte", 0.0), ("influence__lte", 1.0)),
                name="ck_judge_influence",
            ),
        ),
        migrations.AddConstraint(
            model_name="judge",
            constraint=models.UniqueConstraint(
                fields=("label", "court"), name="uq_judge_label_in_court"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationlogentry",
            constraint=models.UniqueConstraint(
                fields=("simulation", "step_no"),
                name="uq_simulation_log_simulation_step_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationparams",
            constraint=models.UniqueConstraint(
                fields=("simulation", "type"), name="uq_params_id_per_type"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationsubmodellogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["additional_info"], name="ix_ssl_additional_info"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationsubmodellogentry",
            constraint=models.UniqueConstraint(
                fields=("log_entry", "submodel_type"),
                name="uq_simulation_submodel_log_log_entry_submodel_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.UniqueConstraint(
                fields=("user", "label"), name="uq_usersettings_user_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("abstention_threshold__gte", 0.0),
                    ("abstention_threshold__lte", 1.0),
                ),
                name="ck_usersettings_abstention_threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legislative_path_probability__gte", 0.0),
                    ("legislative_path_probability__lte", 1.0),
                ),
                name="ck_usersettings_legislative_path_probability",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("government_probability_for__gte", 0.0),
                    ("government_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_government_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parliament_majority_probability_for__gte", 0.0),
                    ("parliament_majority_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_parliament_majority_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parliament_opposition_probability_for__gte", 0.0),
                    ("parliament_opposition_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_parliament_opposition_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("court_probability_for__gte", 0.0),
                    ("court_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_court_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("office_retention_sensitivity__gte", 5.0)),
                name="ck_usersettings_office_retention_sensitivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("social_influence_susceptibility__gte", 0.0),
                    ("social_influence_susceptibility__lte", 1.0),
                ),
                name="ck_usersettings_social_influence_susceptibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.CheckConstraint(
                condition=models.Q(("office_retention_sensitivity__gte", 5.0)),
                name="ck_simulation_office_retention_sensitivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("social_influence_susceptibility__gte", 0.0),
                    ("social_influence_susceptibility__lte", 1.0),
                ),
                name="ck_simulation_social_influence_susceptibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("user_settings", "name"), name="uq_country_user_settings_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualtimeline",
            constraint=models.UniqueConstraint(
                fields=("user_settings", "label"),
                name="uq_virtualtimeline_user_settings_label",
            ),
        ),
    ]
