# Generated by Django 5.2.8 on 2025-12-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("legislative_probability", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Minister",
            fields=[
                ("influence", models.FloatField(default=0.0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("is_prime_minister", models.BooleanField(default=False)),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministers",
                        to="common.cabinet",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ministers",
                        to="common.partysettings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinisterLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "from_minister",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="common.minister",
                    ),
                ),
                (
                    "to_minister",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="common.minister",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minister",
            name="neighbours_out",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="neighbours_in",
                through="common.MinisterLink",
                to="common.minister",
            ),
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="new",
                    ),
                ),
                ("current_step", models.PositiveBigIntegerField(default=0)),
                (
                    "user_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="common.usersettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationParams",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.PositiveBigIntegerField()),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="common.simulation",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ministerlink",
            constraint=models.UniqueConstraint(
                fields=("from_minister", "to_minister"),
                name="uq_ministerlink_no_duplicate_edges",
            ),
        ),
        migrations.AddConstraint(
            model_name="ministerlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_minister", models.F("to_minister")), _negated=True
                ),
                name="ck_ministerlink_no_self_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="minister",
            constraint=models.CheckConstraint(
                condition=models.Q(("influence__gte", 0.0), ("influence__lte", 1.0)),
                name="ck_influencer_influence",
            ),
        ),
        migrations.AddConstraint(
            model_name="minister",
            constraint=models.UniqueConstraint(
                fields=("label", "cabinet"), name="uq_minister_label_in_cabinet"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationparams",
            constraint=models.UniqueConstraint(
                fields=("simulation", "type"), name="uq_params_id_per_type"
            ),
        ),
    ]
