# Generated by Django 6.0.1 on 2026-10-09 18:26

import common.models._institution
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionKind",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("institution_name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Institution kinds",
            },
        ),
        migrations.RemoveConstraint(
            model_name="institutiontaxonomy",
            name="uq_institutiontaxonomy_country_type",
        ),
        migrations.RemoveConstraint(
            model_name="institutiontaxonomy",
            name="ck_institutiontaxonomy_branch",
        ),
        migrations.RemoveConstraint(
            model_name="institution",
            name="uq_institution_taxonomy_label",
        ),
        migrations.RemoveConstraint(
            model_name="institution",
            name="ck_institution_serialization_model",
        ),
        migrations.RemoveConstraint(
            model_name="institution",
            name="ck_institution_serialization_version",
        ),
        migrations.AlterField(
            model_name="institution",
            name="payload",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union,
                    (
                        common.models._institution.CabinetPayload,
                        common.models._institution.ChamberPayload,
                        common.models._institution.CourtPayload,
                    ),
                ),
            ),
        ),
        migrations.AlterField(
            model_name="timeframe",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("institution", "Institution"),
                    ("party_position", "Party Position"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="institutionkind",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_kinds",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="kind",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institutions",
                to="common.institutionkind",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("kind", "label"), name="uq_institution_kind_label"
            ),
        ),
        migrations.RemoveField(
            model_name="institutiontaxonomy",
            name="country",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="institution_taxonomy",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="serialization_model",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="serialization_version",
        ),
        migrations.AddConstraint(
            model_name="institutionkind",
            constraint=models.UniqueConstraint(
                fields=("institution_name", "country"),
                name="uq_institutionkind_institution_name_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="institutionkind",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("branch__in", ["executive", "legislative", "judiciary"])
                ),
                name="ck_institutiontaxonomy_branch",
            ),
        ),
        migrations.DeleteModel(
            name="InstitutionTaxonomy",
        ),
    ]
