# Generated by Django 5.2.8 on 2025-12-18 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_cabinet_minister_ministerlink_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="government_probability_for",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="government_probability_for",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("government_probability_for__gte", 0),
                    ("government_probability_for__lte", 1),
                ),
                name="ck_government_probability_for_is_prob",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("government_probability_for__gte", 0.0),
                    ("government_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_government_probability_for",
            ),
        ),
    ]
