# Generated by Django 5.2.8 on 2025-12-19 16:39

import common.fields._sv_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_cabinet_government_probability_for_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minister",
            name="weights",
            field=common.fields._sv_field.SeparatedValuesField(
                base_field=models.FloatField(), blank=True
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="office_retention_sensitivity",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="simulation",
            name="social_influence_susceptibility",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="office_retention_sensitivity",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="social_influence_susceptibility",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.CheckConstraint(
                condition=models.Q(("office_retention_sensitivity__gte", 5.0)),
                name="ck_simulation_office_retention_sensitivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("social_influence_susceptibility__gte", 0.0),
                    ("social_influence_susceptibility__lte", 1.0),
                ),
                name="ck_simulation_social_influence_susceptibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("office_retention_sensitivity__gte", 5.0)),
                name="ck_usersettings_office_retention_sensitivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("social_influence_susceptibility__gte", 0.0),
                    ("social_influence_susceptibility__lte", 1.0),
                ),
                name="ck_usersettings_social_influence_susceptibility",
            ),
        ),
    ]
