# Generated by Django 6.0.1 on 2026-01-14 17:59

import common.fields._sv_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_minister_weights_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberOfParliament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                ("is_head", models.BooleanField(default=False)),
                (
                    "weights",
                    common.fields._sv_field.SeparatedValuesField(
                        base_field=models.FloatField(), blank=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parliament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("majority_probability_for", models.FloatField(default=0.5)),
                ("opposition_probability_for", models.FloatField(default=0.5)),
            ],
        ),
        migrations.AddField(
            model_name="usersettings",
            name="parliament_majority_probability_for",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="parliament_opposition_probability_for",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parliament_majority_probability_for__gte", 0.0),
                    ("parliament_majority_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_parliament_majority_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parliament_opposition_probability_for__gte", 0.0),
                    ("parliament_opposition_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_parliament_opposition_probability_for",
            ),
        ),
        migrations.AddField(
            model_name="memberofparliament",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="mps",
                to="common.partysettings",
            ),
        ),
        migrations.AddConstraint(
            model_name="parliament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("majority_probability_for__gte", 0),
                    ("majority_probability_for__lte", 1),
                ),
                name="ck_majority_probability_for_is_prob",
            ),
        ),
        migrations.AddConstraint(
            model_name="parliament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opposition_probability_for__gte", 0),
                    ("opposition_probability_for__lte", 1),
                ),
                name="ck_opposition_probability_for_is_prob",
            ),
        ),
        migrations.AddField(
            model_name="memberofparliament",
            name="parliament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="common.parliament",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberofparliament",
            constraint=models.UniqueConstraint(
                fields=("label", "parliament"), name="uq_mp_label_in_parliament"
            ),
        ),
    ]
