# Generated by Django 6.0.1 on 2026-01-15 11:22

import common.fields._sv_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_memberofparliament_parliament_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("probability_for", models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("influence", models.FloatField(default=0.0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50)),
                ("is_president", models.BooleanField(default=False)),
                (
                    "weights",
                    common.fields._sv_field.SeparatedValuesField(
                        base_field=models.FloatField(), blank=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JudgeLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="minister",
            name="ck_influencer_influence",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="court_probability_for",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddConstraint(
            model_name="minister",
            constraint=models.CheckConstraint(
                condition=models.Q(("influence__gte", 0.0), ("influence__lte", 1.0)),
                name="ck_minister_influence",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("court_probability_for__gte", 0.0),
                    ("court_probability_for__lte", 1.0),
                ),
                name="ck_usersettings_court_probability_for",
            ),
        ),
        migrations.AddConstraint(
            model_name="court",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("probability_for__gte", 0), ("probability_for__lte", 1)
                ),
                name="ck_court_probability_for_is_prob",
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judges",
                to="common.court",
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="judges",
                to="common.partysettings",
            ),
        ),
        migrations.AddField(
            model_name="judgelink",
            name="from_judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_edges",
                to="common.judge",
            ),
        ),
        migrations.AddField(
            model_name="judgelink",
            name="to_judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_edges",
                to="common.judge",
            ),
        ),
        migrations.AddField(
            model_name="judge",
            name="neighbours_out",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="neighbours_in",
                through="common.JudgeLink",
                to="common.judge",
            ),
        ),
        migrations.AddConstraint(
            model_name="judgelink",
            constraint=models.UniqueConstraint(
                fields=("from_judge", "to_judge"),
                name="uq_judgelink_no_duplicate_edges",
            ),
        ),
        migrations.AddConstraint(
            model_name="judgelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_judge", models.F("to_judge")), _negated=True),
                name="ck_judgelink_no_self_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="judge",
            constraint=models.CheckConstraint(
                condition=models.Q(("influence__gte", 0.0), ("influence__lte", 1.0)),
                name="ck_judge_influence",
            ),
        ),
        migrations.AddConstraint(
            model_name="judge",
            constraint=models.UniqueConstraint(
                fields=("label", "court"), name="uq_judge_label_in_court"
            ),
        ),
    ]
