# Generated by Django 6.0.1 on 2026-01-20 12:03

import common.models._simulation
import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_court_judge_judgelink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("step_no", models.IntegerField()),
                ("approved", models.BooleanField()),
                (
                    "last_decision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "aggrandisement_path",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("decree", "Decree"),
                            ("legislative act", "Legislative Act"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="common.simulation",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_log",
            },
        ),
        migrations.CreateModel(
            name="SimulationSubmodelLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "submodel_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("legislative", "Legislative"),
                            ("judiciary", "Judiciary"),
                        ]
                    ),
                ),
                ("approved", models.BooleanField()),
                (
                    "additional_info",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing.Union,
                            (
                                common.models._simulation.PathSubmodelInfo,
                                common.models._simulation.VbarSubmodelInfo,
                            ),
                        ),
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submodels",
                        to="common.simulationlogentry",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_submodel_log",
            },
        ),
        migrations.AddConstraint(
            model_name="simulationlogentry",
            constraint=models.UniqueConstraint(
                fields=("simulation", "step_no"),
                name="uq_simulation_log_simulation_step_no",
            ),
        ),
        migrations.AddIndex(
            model_name="simulationsubmodellogentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["additional_info"],
                name="ix_simulation_submodel_log_additional_info",
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationsubmodellogentry",
            constraint=models.UniqueConstraint(
                fields=("log_entry", "submodel_type"),
                name="uq_simulation_submodel_log_log_entry_submodel_type",
            ),
        ),
    ]
