# Generated by Django 6.0.1 on 2026-01-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_simulationlogentry_simulationsubmodellogentry_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="simulationsubmodellogentry",
            new_name="ix_ssl_additional_info",
            old_name="ix_simulation_submodel_log_additional_info",
        ),
    ]
