# Generated by Django 6.0.1 on 2026-03-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_add_belief_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggrandisementBatch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch",
                        to="common.simulation",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AggrandisementUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("step_no", models.PositiveIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="common.aggrandisementbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JudgeBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.judge",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judges",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinisterBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "minister",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.minister",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministers",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MPBelief",
            fields=[
                ("personal_opinion", models.FloatField(default=0)),
                ("appointing_group_opinion", models.FloatField(default=0)),
                ("supporting_group_opinion", models.FloatField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beliefs",
                        to="common.memberofparliament",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mps",
                        to="common.aggrandisementunit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aggrandisementunit",
            constraint=models.UniqueConstraint(
                fields=("step_no", "batch"), name="uq_step_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgebelief",
            constraint=models.UniqueConstraint(
                fields=("judge", "unit"), name="uq_judge_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="ministerbelief",
            constraint=models.UniqueConstraint(
                fields=("minister", "unit"), name="uq_minister_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="mpbelief",
            constraint=models.UniqueConstraint(
                fields=("mp", "unit"), name="uq_mp_unit"
            ),
        ),
    ]
