# Generated by Django 6.0.1 on 2026-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_aggrandisementbatch_aggrandisementunit_judgebelief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggrandisementbatch",
            name="file_name",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
